version: '3'

services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
    web:
        build: .
        command: ["./run_web.sh"]
        volumes:
        - .:/app
        ports:
        - "8000:8000"
        links:
        - db
        depends_on:
        - db