# Generated by Django 2.2 on 2019-12-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191220_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
