# Generated by Django 2.2 on 2019-12-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_ID',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
