# Generated by Django 2.2 on 2019-12-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191220_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_ID',
            field=models.IntegerField(default=1000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
